### PR TITLE
Adding Footer Bubbles

### PR DESCRIPTION
**Pull request by jedtan**

### CODE REVIEW

**Review by kmjennison — CHANGES_REQUESTED** [review]
The color of these footer bubbles depends on the cause. See mocks: they should be a lighter orange for cats, a darker blue on seas, and a darker purple on Black equity.

**Comment by jedtan** [comment]
Requested the review too early 😂 , my bad!

**Review by kmjennison — CHANGES_REQUESTED** [review]
(Not sure if this is ready for review or not. Sorry if this premature.)

There are a some divergences from [mocks](https://www.figma.com/file/U69FDY32xoACHgIxyQaGD0/TFC-Brand-Visuals-Exploration?node-id=432%3A736):
* There should be two footer blobs
* The current blob's layout on desktop is a bit off (too low)
* The current blob's layout on mobile is very off

**Comment by jedtan** [comment]
Before my commit I was able to see both bubbles. I have played around a little bit with it to make it more correct, but I think there may also be an existing bug with the position of the cat. Asides from the left bubble on mobile being off to me it felt pretty close? Maybe I'm seeing something different locally.

image

image

**Comment by jedtan** [comment]
I guess the right one on mobile is quite high, but that's due to the presence of the cat - should I adjust the cat too?

**Comment by kmjennison** [comment]
@jedtan Could you put this on dev to mess around? I was reviewing on Chromatic, and I'm wondering if the lack of the second bubble was just because the svg didn't load before the snapshot.

As for the footer image, I think it's probably fine (?) but would need to look at behavior at different widths. I'm guessing your screenshot above is when the screen is closer to tablet width than desktop, and we plan to revisit the tablet responsiveness later.

**Comment by jedtan** [comment]
Ah, looks like you're right. I think my desktop is ~tablet sized in storybook. Will update.

**Review by kmjennison — APPROVED** [review]
LGTM 🦊

**Pull request merged**
